src/main/java/com/newstoss/global/config/SecurityConfig.java, src/main/java/com/newstoss/member/adapter/in/web/MemberController.java
=> [FIX] security 모든 경로 허용(개발용)

src/main/java/com/newstoss/member/adapter/in/web/MemberController.java, src/main/java/com/newstoss/member/adapter/in/web/dto/requestDTO/DuplicateDTO.java, src/main/java/com/newstoss/member/application/MemberService.java, src/main/java/com/newstoss/member/application/command/SignupService.java, src/main/java/com/newstoss/member/application/query/DuplicateCheck.java
=> [FEAT] id중복 체크 api 생성

.github/workflows/ci.yml, Dockerfile
=> [FIX] CD, Dockerfile 수정

.github/workflows/cd.yml
=> [FIX] cd 수정 4

.github/workflows/cd.yml
=> [FIX] cd 수정 5

.github/workflows/cd.yml
=> [FIX] cd 수정 7

.github/workflows/ci.yml, Dockerfile
close #25 
CI 과정에서 불필요한 과정을 제거하고, 최적화함.
현재 과정
pr 생성 : 깃허브 레포지토리에 있는 코드를 build -> 빌드한 코드를 아티팩트(JAR 파일)로 저장
main 브랜치에 push : 저장한 아티팩트를 다운로드 받아서 도커 이미지로 만듬 -> 도커 이미지 ECR에 푸쉬
=> [FIX] ci 최적화

src/main/java/com/newstoss/auth/application/command/LoginService.java, src/main/java/com/newstoss/global/config/PasswordEncoderConfig.java, src/main/java/com/newstoss/global/config/SecurityConfig.java, src/main/java/com/newstoss/global/errorcode/JwtErrorCode.java, src/main/java/com/newstoss/global/jwt/JwtAccessDeniedHandler.java, src/main/java/com/newstoss/global/jwt/JwtAuthenticationEntryPoint.java, src/main/java/com/newstoss/global/jwt/JwtProvider.java, src/main/java/com/newstoss/member/adapter/out/persistence/JpaMemberRepository.java, src/main/java/com/newstoss/member/adapter/out/persistence/MemberAdapter.java, src/main/java/com/newstoss/member/application/command/SignupService.java, src/main/java/com/newstoss/member/domain/Member.java
=> [FIX] jwt 에러 핸들링 추가 및 password 해시 처리

src/main/java/com/newstoss/stock/adapter/inbound/api/v1/StockApiController.java, src/main/java/com/newstoss/stock/adapter/inbound/dto/response/CategoryStockResponseDto.java, src/main/java/com/newstoss/stock/application/StockQueryService.java
=> [FIX] 주식 카테고리 api 수정

src/main/java/com/newstoss/auth/application/command/LoginService.java, src/main/java/com/newstoss/global/jwt/JwtProvider.java
=> [FIX] JWT 포함 정보 수정

src/main/java/com/newstoss/news/adapter/in/web/controller/NewsControllerV1.java, src/main/java/com/newstoss/news/adapter/in/web/controller/NewsControllerV2.java, src/main/java/com/newstoss/news/application/impl/GetRealTimeNewsWithSSE.java, src/main/java/com/newstoss/news/application/impl/GetRelatedNews.java, src/main/java/com/newstoss/news/application/impl/GetRelatedReport.java, src/main/java/com/newstoss/news/application/impl/GetRelatedStocks.java, src/main/java/com/newstoss/news/application/impl/v1/GetDetailNewsV1.java, src/main/java/com/newstoss/news/application/impl/v1/GetRealTimeNewsV1.java, src/main/java/com/newstoss/news/application/impl/v1/NewsDTOv1Mapper.java, src/main/java/com/newstoss/news/application/impl/v2/GetDetailNewsV2.java, src/main/java/com/newstoss/news/application/impl/v2/GetRealTimeNewsV2.java, src/main/java/com/newstoss/news/application/impl/v2/NewsDTOv2Mapper.java, src/main/java/com/newstoss/news/application/port/in/ml/GetRelatedNewsUseCase.java, src/main/java/com/newstoss/news/application/port/in/ml/GetRelatedReportUseCase.java, src/main/java/com/newstoss/news/application/port/in/ml/GetRelatedStocksUseCase.java, src/main/java/com/newstoss/news/application/port/in/ml/v1/GetNewsDetailUseCaseV1.java, src/main/java/com/newstoss/news/application/port/in/ml/v1/GetRealTimeNewsUseCaseV1.java, src/main/java/com/newstoss/news/application/port/in/ml/v2/GetNewsDetailUseCaseV2.java, src/main/java/com/newstoss/news/application/port/in/ml/v2/GetRealTimeNewsUseCaseV2.java, src/main/java/com/newstoss/news/application/service/NewsServiceV1.java, src/main/java/com/newstoss/news/application/service/NewsServiceV2.java, src/main/java/com/newstoss/news/domain/NewsScrap.java
=> [FIX] 파일 구조 변경

.github/workflows/cd.yml, .github/workflows/ci.yml
=> [FIX] ci, cd 수정

src/main/java/com/newstoss/global/init/StockInit.java, src/main/java/com/newstoss/portfolio/entity/Portfolio.java, src/main/java/com/newstoss/stock/adapter/inbound/api/v1/StockApiController.java, src/main/java/com/newstoss/stock/adapter/inbound/api/v1/kis/StockKisController.java, src/main/java/com/newstoss/stock/adapter/inbound/dto/response/CategoryStockResponseDto.java, src/main/java/com/newstoss/stock/adapter/inbound/dto/response/IndicesResponseDto.java, src/main/java/com/newstoss/stock/adapter/outbound/kis/GetIndiceInfoClient.java, src/main/java/com/newstoss/stock/adapter/outbound/kis/GetKisStockClient.java, src/main/java/com/newstoss/stock/adapter/outbound/kis/GetPopularStockService.java, src/main/java/com/newstoss/stock/adapter/outbound/kis/dto/KisIndiceInfoDto.java, src/main/java/com/newstoss/stock/adapter/outbound/kis/dto/KisPeriodStockDto.java, src/main/java/com/newstoss/stock/adapter/outbound/persistence/repository/StockRepository.java, src/main/java/com/newstoss/stock/adapter/outbound/persistence/repository/StockRepositoryImpl.java, src/main/java/com/newstoss/stock/application/IndiceService.java, src/main/java/com/newstoss/stock/application/StockInfoService.java, src/main/java/com/newstoss/stock/application/StockPopularService.java, src/main/java/com/newstoss/stock/application/StockQueryService.java, src/main/java/com/newstoss/stock/application/port/in/GetCategoryUseCase.java, src/main/java/com/newstoss/stock/application/port/in/GetIndiceUseCase.java, src/main/java/com/newstoss/stock/application/port/in/GetPopularStockUseCase.java, src/main/java/com/newstoss/stock/application/port/in/GetStockInfoUseCase.java, src/main/java/com/newstoss/stock/application/port/in/SearchStockUseCase.java, src/main/java/com/newstoss/stock/application/port/out/kis/KisIndicePort.java, src/main/java/com/newstoss/stock/application/port/out/kis/KisPopularStockPort.java, src/main/java/com/newstoss/stock/application/port/out/kis/KisStockInfoPort.java, src/main/java/com/newstoss/stock/application/port/out/persistence/StockRepositoryCustom.java, src/main/java/com/newstoss/stock/entity/Stock.java
=> [FIX] 증권 api 수정

.github/workflows/cd.yml
close 
-e SERVER_TOMCAT_MBEANREGISTRY_ENABLED=true  환경변수 추가
=> [FIX] cd.yml 수정

src/main/java/com/newstoss/global/kis/KisTokenManager.java
=> [FIX] KIS 토큰 매니저 수정

src/main/java/com/newstoss/portfolio/application/MemberPnlSchedularService.java
=> [FEAT]  포트폴리오 관련 api 개발

src/main/java/com/newstoss/calender/CalendarController.java, src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteController.java
=> [FIX] 캘린더, 관심종목 수정

src/main/java/com/newstoss/global/redis/NewsRedisSubscriber.java
=> [FIX] redis설정 변경

src/main/java/com/newstoss/news/adapter/in/web/sse/NewsSseController.java, src/main/java/com/newstoss/news/adapter/in/web/sse/SseEmitters.java
=> [FIX] redis설정

src/main/java/com/newstoss/news/adapter/in/web/sse/NewsSseController.java
=> [FEAT] CORS 설정

src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteController.java, src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteService.java
close 
관심 그룹 추가 시 반환값 나오도록 수정
관심 그룹 이름 변경 기능 추가
=> [FEAT] 관심그룹 이름 변경 기능 추가

src/main/java/com/newstoss/member/adapter/in/web/MemberController.java, src/main/java/com/newstoss/member/application/MemberService.java, src/main/java/com/newstoss/member/application/in/command/InvestScoreService.java, src/main/java/com/newstoss/member/domain/Member.java
=> [FEAT] invest_score 수정 api 구현

src/main/java/com/newstoss/news/adapter/out/redis/HighlightNewsScheduler.java
=> [FIX] prod확인용 로그 추가

src/main/java/com/newstoss/stock/adapter/inbound/api/v1/StockSideBarController.java, src/main/java/com/newstoss/stock/adapter/outbound/persistence/JpaCommandRepositoryAdapter.java, src/main/java/com/newstoss/stock/application/FxInfoService.java, src/main/java/com/newstoss/stock/application/StockCommandService.java, src/main/java/com/newstoss/stock/application/port/out/persistence/StockSearchCounterPort.java
=> [FIX] 주식 api 수정

src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV1.java, src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java, src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java
=> ML api endpoint 수정으로 인한 변경

src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/IndustryListDTO.java, src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/NewsMetaDataDTO.java, src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RelatedStockDTOv2.java, src/main/java/com/newstoss/news/adapter/in/web/sse/SseEmitters.java, src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLIndustryListDTO.java, src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLNewsMataDataDTOv2.java, src/main/java/com/newstoss/news/application/news/v2/impl/NewsDTOv2Mapper.java, src/main/java/com/newstoss/news/application/redis/impl/HighlightNewsCacheService.java, src/main/java/com/newstoss/portfolio/application/MemberPnlSchedulerService.java, src/main/java/com/newstoss/portfolio/entity/MemberPnl.java
=> [FIX] ml api 스펙 변경 반영

src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java, src/main/java/com/newstoss/news/adapter/in/web/sse/NewsSseController.java, src/main/java/com/newstoss/news/adapter/in/web/sse/SseEmitters.java, src/main/java/com/newstoss/news/adapter/out/redis/NewsRedisSubscriber.java, src/test/java/com/newstoss/portfolio/application/PortfolioStockQueryServiceTest.java, src/test/java/com/newstoss/sse/SseEmittersTest.java
=> [FIX} SSE emitter 설정

src/main/java/com/newstoss/global/handler/GlobalExceptionHandler.java, src/main/java/com/newstoss/news/adapter/in/web/sse/SseEmitters.java
=> [FIX]TomCat 에러 잡기

src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/ChatMessage.java, src/main/java/com/newstoss/news/adapter/in/web/sse/controller/ChatSseController.java, src/main/java/com/newstoss/news/application/redis/ChatStreamService.java
=> [FIX] dto Key 값 성정

src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RealTimeNewsDTO.java, src/main/java/com/newstoss/news/adapter/in/web/sse/controller/ChatSseController.java, src/main/java/com/newstoss/news/adapter/in/web/sse/dto/ChatStreamRequest.java, src/main/java/com/newstoss/news/adapter/in/web/sse/dto/ChatStreamResponse.java, src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java, src/main/java/com/newstoss/news/adapter/out/redis/chatbot/ChatRedisSubscriber.java, src/main/java/com/newstoss/news/application/news/v2/port/out/MLNewsPortV2.java
=> [FEAT] 챗봇 api

src/main/java/com/newstoss/global/kis/dto/KisApiRequestDto.java, src/main/java/com/newstoss/global/kis/stream/KisApiStreamProducer.java, src/main/java/com/newstoss/stock/application/stream/KisApiStreamConsumer.java
=> [FIX] Stock api 수정

.github/workflows/cd.yml, Dockerfile, src/main/java/com/newstoss/news/application/news/v2/impl/ml/GetDetailNewsV2.java, src/main/resources/logback-spring.xml
=> [FEAT] 뉴스 로그 추가

src/main/java/com/newstoss/news/application/news/service/NewsLogsService.java
=> [FIX] 뉴스 로그 파싱 수정

src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
=> [FIX] 하이라이트 뉴스 주석 제거

src/main/java/com/newstoss/global/config/SecurityConfig.java, src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java
=> [FIX] 원상태 되돌리기

src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java, src/main/java/com/newstoss/news/application/news/service/NewsServiceV2.java, src/main/java/com/newstoss/news/application/news/v2/impl/ml/GetDetailNewsV2.java, src/main/java/com/newstoss/news/application/news/v2/port/in/GetNewsDetailUseCaseV2.java
=> [FIX] 원상태 복귀

src/main/java/com/newstoss/global/config/SecurityConfig.java
=> [FIX] SecurityConfig requestMatchers 조건 바꾸기

src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java, src/main/java/com/newstoss/member/application/in/command/CustomUserDetailsService.java, src/main/java/com/newstoss/member/domain/Member.java, src/main/java/com/newstoss/member/domain/UserAccount.java, src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
=> [FIX] userAccount로 변경

src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
=> [FIX] 쿠키밸류로 값 끄네기

src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
=> [FIX] crossorigin 조건 변경

src/main/java/com/newstoss/auth/adapter/in/web/AuthController.java
=> [FIX] samesite 설정

src/main/java/com/newstoss/global/config/WebConfig.java
=> [FIX] CORS 설정

src/main/java/com/newstoss/stock/application/V1/StockInfoService.java
=> [FIX] 긴급 복구

src/main/java/com/newstoss/global/config/SecurityConfig.java, src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java, src/main/java/com/newstoss/global/jwt/JwtProvider.java
=> [FIX] endpoint 수정

src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java, src/main/java/com/newstoss/news/application/redis/ChatStreamService.java
=> [FIX] 챗봇 GET으로 변경

src/main/java/com/newstoss/global/config/SecurityConfig.java
=> [FIX] 프로메테우스 설정

src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java, src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
=> [TEST] 챗봇 테스트

src/main/java/com/newstoss/news/application/news/v2/impl/NewsDTOv2Mapper.java
=> [FIX] DTO 수정

src/main/java/com/newstoss/stock/application/V1/StockInfoService.java
=> [FIX]일봉 2000일로 수정, 주봉 안되던거 수정

src/main/java/com/newstoss/calender/CalendarController.java, src/main/java/com/newstoss/calender/CalendarRepository.java, src/main/java/com/newstoss/global/errorcode/ScrapErrorCode.java
=> [FEAT] 캘린더 마켓 구분 조회 기능 추가

src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
=> [FIX] 중복 처리 로직 수정

src/main/java/com/newstoss/news/adapter/in/web/scrap/controller/ScrapNewsController.java, src/main/java/com/newstoss/news/adapter/in/web/scrap/dto/ExternalNewsDTO.java, src/main/java/com/newstoss/news/adapter/out/scrap/ScrapNewsAdapter.java, src/main/java/com/newstoss/news/adapter/out/scrap/repository/JpaNewsScrapRepository.java, src/main/java/com/newstoss/news/application/scrap/impl/GetScrapNewsList.java, src/main/java/com/newstoss/news/application/scrap/impl/SaveScrapNews.java, src/main/java/com/newstoss/news/domain/NewsScrap.java
=> [FIX] 뉴스 스크랩 ml API로 연동

src/main/java/com/newstoss/stock/entity/StockHistory.java
=> [FIX] sse,redis 삭제

src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
=> [FIX] 챗봇 로그 추가

src/main/java/com/newstoss/calender/Calendar.java, src/main/java/com/newstoss/calender/CalendarController.java, src/main/java/com/newstoss/calender/CalendarRepository.java
=> [FIX] 캘린더 수정

src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RealTimeNewsDTO.java, src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
=> [FIX] 챗봇 쓰레드 풀 갯수 지정

src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RealTimeNewsDTO.java
=> [FIX] dto수정

src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java, src/main/java/com/newstoss/news/adapter/out/redis/highlight/HighlightNewsScheduler.java, src/main/java/com/newstoss/news/adapter/out/redis/realtime/RealTimeNewsCache.java, src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java, src/main/java/com/newstoss/news/application/redis/RealTimeService.java, src/main/java/com/newstoss/news/application/redis/impl/HighlightNewsCacheImpl.java, src/main/java/com/newstoss/news/application/redis/impl/RealTimeNewsCacheImpl.java, src/main/java/com/newstoss/news/application/redis/port/in/RealTimeNewsCacheUseCase.java, src/main/java/com/newstoss/news/application/redis/port/out/RealTimeNewsCachePort.java
=> [TEST] 시간 로그 추가

src/main/java/com/newstoss/news/adapter/out/redis/highlight/HighlightNewsCache.java, src/main/java/com/newstoss/news/adapter/out/redis/realtime/RealTimeNewsCache.java, src/main/java/com/newstoss/news/application/redis/impl/RealTimeNewsCacheImpl.java, src/main/java/com/newstoss/news/application/redis/port/in/RealTimeNewsCacheUseCase.java, src/main/java/com/newstoss/news/application/redis/port/out/RealTimeNewsCachePort.java
=> [FIX] 빈 이름 중복 제거

src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java
=> [FIX] 에러 로그 세분화

src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/HighlightNewsDTO.java, src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/Meta/RelatedNewsDTOv2.java, src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/NewsDTOv2.java, src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RecommendNewsDTO.java, src/main/java/com/newstoss/news/adapter/in/web/scrap/dto/LogNewsDTO.java, src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java, src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLHighlightNewsDTOv2.java, src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLNewsDTOv2.java, src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLRecommendNewsDTO.java, src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLRelatedNewsDTOv2.java, src/main/java/com/newstoss/news/application/news/v2/impl/NewsDTOv2Mapper.java, src/main/java/com/newstoss/news/application/scrap/impl/GetScrapNewsList.java
=> [FIX] 뉴스 DTO 수정

build.gradle, src/main/java/com/newstoss/global/config/MLRestTemplateConfig.java, src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java, src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/CountDTO.java, src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/NewsDTOv2.java, src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java, src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLNewsCountDTO.java, src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLNewsDTOv2.java, src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java, src/main/java/com/newstoss/news/application/news/service/NewsServiceV2.java, src/main/java/com/newstoss/news/application/news/v2/impl/NewsDTOv2Mapper.java, src/main/java/com/newstoss/news/application/news/v2/impl/ml/GetNewsCount.java, src/main/java/com/newstoss/news/application/news/v2/port/in/GetNewsCountUseCaseV2.java, src/main/java/com/newstoss/news/application/news/v2/port/out/MLNewsPortV2.java
=> 뉴스 갯수 api 생성 및 커넥션 풀 설정

src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java, src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsLogsController.java, src/main/java/com/newstoss/news/application/news/service/NewsLogRecordService.java, src/main/java/com/newstoss/news/application/news/service/NewsServiceV2.java, src/main/java/com/newstoss/news/application/news/v2/impl/ml/GetDetailNewsV2.java, src/main/java/com/newstoss/news/application/news/v2/port/in/GetNewsDetailUseCaseV2.java
=> [FEAT] 뉴스 로그 api 생성, 기존 상세 뉴스 조회에서 로그 기능 제거

src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RealTimeNewsDTO.java
=> [FIX] 실시간 뉴스 DTO 수정

src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java, src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java, src/main/java/com/newstoss/news/application/redis/ChatStreamService.java
=> [TEST] log 메세지 수정

src/main/java/com/newstoss/global/config/MLWebClientConfig.java, src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
=> [FIX] 챗봇 서버 변경

src/main/java/com/newstoss/favorite/FavoriteGroup/Favorite.java, src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteService.java, src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStock.java, src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockRepository.java
=> [FIX] 관심 그룹 삭제하면 안의 관심 종목도 제거

src/main/java/com/newstoss/favorite/FavoriteGroup/Favorite.java, src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteRepository.java, src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteService.java, src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStock.java
=> Fix : 관심그룹 버그 수정

src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStock.java, src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockController.java, src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockRepository.java, src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockService.java, src/main/java/com/newstoss/favorite/adapter/out/ExternalStockApiClient.java, src/main/java/com/newstoss/favorite/adapter/out/dto/ExternalStockApiResponse.java, src/main/java/com/newstoss/global/errorcode/FavoriteErrorCode.java
=> [FIX] 증권 API에서 값 불러오도록 수정
